# Generated by Django 5.2.6 on 2025-09-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Battery", " Battery"),
                            ("Brakepads", "Brakepads"),
                            ("Cleaner", "Cleaner"),
                            ("Coolant", " Coolant"),
                            ("Filters", "Filters"),
                            ("Linkages", "Linkages"),
                            ("Lubricants", "Lubricants"),
                            ("Tires", "Tires"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile/photos/"
                    ),
                ),
                ("Quantity", models.IntegerField()),
                ("unit_price", models.IntegerField()),
                ("unit_cost", models.IntegerField()),
                ("sales_unit", models.IntegerField()),
                ("sku", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productcategory",
                    ),
                ),
            ],
        ),
    ]
